### ISSUE TITLE
Create new record using GraphhQL + Node.js [Mutation]

### ISSUE THREAD

**Issue by ashokdey** [knaxus/rest-and-graphql#6]
The REST API part is complete and working fine, however, the CRUD is not implemented in GraphQL

What is required?
- Create a new record using GrapQL mutations
- Follow ESLint rules
- Make sure app is not breaking before raising your PR
- Add screenshots of working demo using GraphQL when submitting your PR

Add a ⭐️ if you like working on it!

**Comment by souravdasslg** [comment]
![image](https://user-images.githubusercontent.com/9268592/66372581-f338ef00-e9c3-11e9-9d23-757585ec0931.png)
Hi @ashokdey , I'd love to contribute here.

**Comment by ashokdey** [comment]
Welcome onboard @souravdasslg. I am assigning you this task. 🎉

**Comment by souravdasslg** [comment]
Thanks :). I'll start working on this soon

**Comment by ashokdey** [comment]
#8 closes this
